### ISSUE TITLE
is there a way to validate and reprompt on bad input?

### ISSUE THREAD

**Issue by mreinstein** [npm/promzard#3]
neat module @isaacs I'm wondering if there's a way to reprompt when a field fails validation? For instance example/npm-init/init-input.js reads version, but there's nothing preventing me from typing 'heh' at the prompt and having that accepted. I'd want to enforce semver for this field, and ditto for other field types. I looked at isaacs/npm/blob/master/lib/adduser.js to see how this was achieved, and notice it doesnt rely on promzard (uses your read package at a lower level.) Is this an intentional design decision, or what?

**Comment by lukekarrys** [comment]
This was added in 4d5c6474c45f176d179fce69513f0b220b98e031. You can return an error with a `notValid` property to retry.
