### ISSUE TITLE
Conditional prompts and conditional object creation

### ISSUE THREAD

**Issue by mfncooper** [npm/promzard#4]
I'm not seeing a way to prompt conditionally or conditionally create an object. As a concrete example of both, consider a fancier way of prompting for the repository information from `npm init`. First, we prompt for the repo type:

```
repository type:
```

Now, if the user enters a value, we would prompt for the repository itself:

```
git repository:
-or-
svn repository:
```

(Yes, I know having different prompts in this case is silly; it's just a convenient example.)

If the user entered no value for repository type, though, we would not prompt for the repository URL at all.

If the user then enters a URL, the result would be:

```
{ type: "git", url: "my git url" }
```

but if the user did not enter a URL (or did not enter a type), we would leave the result undefined (i.e. no object at all), so that none of the repository structure would show up in package.json.

Is there a way to do this?

**Comment by lukekarrys** [comment]
this is now (partially) possible in `1.0.0`. you can access the current state within the context passed to each function as `this.res`. but you're still responsible for cleaning up the object before it is finished, `promzard` wont do that for you.

here's some code for the example above:

```js
module.exports = {
  repository: {
    type: prompt('repo type'),
    url () {
      if (['git', 'svn'].includes(this.res.repository.type)) {
        return prompt(`${this.res.repository.type} url`)
      }
    },
  },
  // this name of this doesnt matter, just that it comes last
  '' () {
    if (!this.res.repository.type || !this.res.repository.url) {
      delete this.res.repository
    }
  },
}
```
